### ISSUE TITLE
Manual permission handling (on MacOS)

### ISSUE THREAD

**Issue by tillbaks** [nut-tree/libnut-core#141]
**Short overview**
Add ability to manually show the permissions dialog depending on what permissions are actually used by the software depending on libnut.

**Use case**
1. If using only the keyboard part - any users would still get the screen recording permission dialog. Which might be confusing/unexpected for users.
2.  Ability to display a message before permission is requested to explain to the user why the permission will be requested to prevent users denying a necessary permission and then being confused why it is not working. 
3. Ability to know if a required permission is disabled so  features of the software can be disabled or display warning why it does not work.

**Comment by s1hofmann** [comment]
More fine-grained permission requests are already in place.
Explicit requests can be carried out using https://www.npmjs.com/package/@nut-tree/node-mac-permissions
