### ISSUE TITLE
Duplicate key entires?

### ISSUE THREAD

**Issue by smithkyle** [nut-tree/libnut-core#167]
I was curious about this when I added fa2b880 - are the lines below duplicated for a reason?

https://github.com/nut-tree/libnut-core/blob/fa2b880a7742cd9fa3656553aa44c523bd3809fb/src/main.cc#L303-L307
https://github.com/nut-tree/libnut-core/blob/fa2b880a7742cd9fa3656553aa44c523bd3809fb/src/main.cc#L309-L313

**Comment by s1hofmann** [comment]
Hi @smithkyle 👋 

Short answer: No.

Must've happened by accident.

All the best

Simon
